"""Seed script to populate the database with initial data."""
import asyncio
import uuid
from datetime import date, timedelta
from decimal import Decimal

from sqlalchemy import select

from app.config import settings
from app.db.session import async_session_factory
from app.db.base import Base
from app.db.session import engine
from app.auth.security import hash_password
from app.models.user import User, UserRole
from app.models.subscription import SubscriptionPlan
from app.models.source import Source, SourceType
from app.models.property import (
    AuctionProperty, PropertyType, PropertySubtype, PossessionStatus, AuctionStatus,
)


SUBSCRIPTION_PLANS = [
    {
        "name": "Free",
        "price": 0,
        "duration_days": 36500,
        "features": {"search": True, "view_details": True, "saved_searches": 3, "alerts": 1},
        "max_saved_searches": 3,
        "max_alerts": 1,
        "can_export": False,
        "api_access": False,
    },
    {
        "name": "Pro",
        "price": 999,
        "duration_days": 30,
        "features": {
            "search": True, "view_details": True, "saved_searches": 20,
            "alerts": 10, "export_csv": True, "price_history": True,
        },
        "max_saved_searches": 20,
        "max_alerts": 10,
        "can_export": True,
        "api_access": False,
    },
    {
        "name": "Enterprise",
        "price": 4999,
        "duration_days": 30,
        "features": {
            "search": True, "view_details": True, "saved_searches": -1,
            "alerts": -1, "export_csv": True, "export_pdf": True,
            "api_access": True, "priority_support": True, "bulk_download": True,
        },
        "max_saved_searches": 999,
        "max_alerts": 999,
        "can_export": True,
        "api_access": True,
    },
]

SOURCES = [
    {
        "name": "IBAPI (Indian Banks Auctions Portal)",
        "source_type": SourceType.website,
        "base_url": "https://ibapi.in",
        "crawler_module": "app.ingestion.sources.sample_bank.SampleBankCrawler",
        "schedule_cron": "0 2 * * *",
        "config": {"max_pages": 50},
    },
    {
        "name": "SBI e-Auction",
        "source_type": SourceType.website,
        "base_url": "https://sbi.co.in/web/sbi-in-the-news/auction-notices",
        "crawler_module": "app.ingestion.sources.sample_bank.SampleBankCrawler",
        "schedule_cron": "0 3 * * *",
        "config": {"bank_name": "State Bank of India", "max_pages": 20},
    },
    {
        "name": "Bank Auction PDF Notices",
        "source_type": SourceType.pdf,
        "base_url": None,
        "crawler_module": "app.ingestion.sources.pdf_parser.PDFParserCrawler",
        "schedule_cron": "0 4 * * *",
        "config": {"ocr_enabled": True},
    },
]

SAMPLE_PROPERTIES = [
    {
        "bank_name": "State Bank of India",
        "bank_branch": "Andheri West Branch",
        "title": "2BHK Flat in Andheri West, Mumbai",
        "description": "Well-maintained 2BHK flat with car parking, located in a prime locality of Andheri West. Close to metro station and market.",
        "property_type": PropertyType.residential,
        "property_subtype": PropertySubtype.flat,
        "address": "Flat No 302, Sunshine Towers, SV Road, Andheri West",
        "locality": "Andheri West",
        "city": "Mumbai",
        "state": "Maharashtra",
        "pin_code": "400058",
        "reserve_price": 8500000,
        "emd_amount": 850000,
        "bid_increment": 50000,
        "auction_date": date(2026, 4, 15),
        "auction_time": "11:00 AM",
        "possession_status": PossessionStatus.symbolic,
        "area_sqft": 950,
        "contact_person": "Mr. R. Sharma",
        "contact_phone": "022-26281234",
    },
    {
        "bank_name": "Punjab National Bank",
        "bank_branch": "Connaught Place Branch",
        "title": "Commercial Office Space in Connaught Place, Delhi",
        "description": "Prime commercial office space in the heart of Connaught Place. Suitable for corporate offices.",
        "property_type": PropertyType.commercial,
        "property_subtype": PropertySubtype.office,
        "address": "2nd Floor, Block A, Connaught Place",
        "locality": "Connaught Place",
        "city": "New Delhi",
        "state": "Delhi",
        "pin_code": "110001",
        "reserve_price": 35000000,
        "emd_amount": 3500000,
        "bid_increment": 100000,
        "auction_date": date(2026, 4, 20),
        "auction_time": "2:00 PM",
        "possession_status": PossessionStatus.physical,
        "area_sqft": 2200,
        "contact_person": "Mr. A. Kumar",
        "contact_phone": "011-23456789",
    },
    {
        "bank_name": "HDFC Bank",
        "bank_branch": "Koramangala Branch",
        "title": "3BHK Villa in Whitefield, Bangalore",
        "description": "Spacious 3BHK independent villa with garden. Gated community with 24/7 security.",
        "property_type": PropertyType.residential,
        "property_subtype": PropertySubtype.house,
        "address": "Villa No 15, Palm Meadows, Whitefield",
        "locality": "Whitefield",
        "city": "Bangalore",
        "state": "Karnataka",
        "pin_code": "560066",
        "reserve_price": 15000000,
        "emd_amount": 1500000,
        "bid_increment": 100000,
        "auction_date": date(2026, 4, 18),
        "auction_time": "10:00 AM",
        "possession_status": PossessionStatus.symbolic,
        "area_sqft": 2800,
        "contact_person": "Ms. P. Reddy",
        "contact_phone": "080-41234567",
    },
    {
        "bank_name": "Bank of Baroda",
        "bank_branch": "Satellite Branch",
        "title": "Commercial Shop in SG Highway, Ahmedabad",
        "description": "Ground floor commercial shop in a busy commercial complex on SG Highway.",
        "property_type": PropertyType.commercial,
        "property_subtype": PropertySubtype.shop,
        "address": "Shop No 5, Galaxy Complex, SG Highway",
        "locality": "SG Highway",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "pin_code": "380054",
        "reserve_price": 4500000,
        "emd_amount": 450000,
        "bid_increment": 25000,
        "auction_date": date(2026, 5, 1),
        "auction_time": "11:30 AM",
        "possession_status": PossessionStatus.physical,
        "area_sqft": 600,
        "contact_person": "Mr. J. Patel",
        "contact_phone": "079-26543210",
    },
    {
        "bank_name": "ICICI Bank",
        "bank_branch": "T Nagar Branch",
        "title": "Residential Plot in OMR, Chennai",
        "description": "Residential plot in a developing area along OMR. All approvals in place.",
        "property_type": PropertyType.land,
        "property_subtype": PropertySubtype.plot,
        "address": "Plot No 42, Perungudi Layout, OMR",
        "locality": "Perungudi",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "pin_code": "600096",
        "reserve_price": 6000000,
        "emd_amount": 600000,
        "bid_increment": 50000,
        "auction_date": date(2026, 4, 25),
        "auction_time": "3:00 PM",
        "possession_status": PossessionStatus.physical,
        "area_sqft": 2400,
        "contact_person": "Mr. S. Iyer",
        "contact_phone": "044-28765432",
    },
    {
        "bank_name": "Union Bank of India",
        "bank_branch": "Salt Lake Branch",
        "title": "3BHK Flat in Salt Lake, Kolkata",
        "description": "Well-located 3BHK flat in Sector V, Salt Lake. Close to IT hub.",
        "property_type": PropertyType.residential,
        "property_subtype": PropertySubtype.flat,
        "address": "Flat 4B, Block CF, Sector V, Salt Lake",
        "locality": "Salt Lake Sector V",
        "city": "Kolkata",
        "state": "West Bengal",
        "pin_code": "700091",
        "reserve_price": 5500000,
        "emd_amount": 550000,
        "bid_increment": 25000,
        "auction_date": date(2026, 4, 22),
        "auction_time": "12:00 PM",
        "possession_status": PossessionStatus.symbolic,
        "area_sqft": 1400,
        "contact_person": "Mr. D. Banerjee",
        "contact_phone": "033-23456789",
    },
    {
        "bank_name": "Canara Bank",
        "bank_branch": "Baner Branch",
        "title": "Industrial Warehouse in Chakan, Pune",
        "description": "Large industrial warehouse with loading dock. Suitable for manufacturing or logistics.",
        "property_type": PropertyType.industrial,
        "property_subtype": PropertySubtype.warehouse,
        "address": "Plot 78, MIDC Chakan, Phase II",
        "locality": "Chakan MIDC",
        "city": "Pune",
        "state": "Maharashtra",
        "pin_code": "410501",
        "reserve_price": 22000000,
        "emd_amount": 2200000,
        "bid_increment": 200000,
        "auction_date": date(2026, 5, 5),
        "auction_time": "11:00 AM",
        "possession_status": PossessionStatus.physical,
        "area_sqft": 10000,
        "contact_person": "Mr. V. Kulkarni",
        "contact_phone": "020-67891234",
    },
    {
        "bank_name": "State Bank of India",
        "bank_branch": "Gomti Nagar Branch",
        "title": "4BHK Independent House in Gomti Nagar, Lucknow",
        "description": "Spacious independent house with lawn, located in Gomti Nagar Extension.",
        "property_type": PropertyType.residential,
        "property_subtype": PropertySubtype.house,
        "address": "House No 12, Sector 6, Gomti Nagar Extension",
        "locality": "Gomti Nagar",
        "city": "Lucknow",
        "state": "Uttar Pradesh",
        "pin_code": "226010",
        "reserve_price": 9500000,
        "emd_amount": 950000,
        "bid_increment": 50000,
        "auction_date": date(2026, 4, 28),
        "auction_time": "10:00 AM",
        "possession_status": PossessionStatus.symbolic,
        "area_sqft": 3200,
        "contact_person": "Mr. R. Tiwari",
        "contact_phone": "0522-4567890",
    },
    {
        "bank_name": "Bank of India",
        "bank_branch": "Bandra Branch",
        "title": "Sea-facing 2BHK in Bandra West, Mumbai",
        "description": "Luxurious sea-facing 2BHK apartment in a premium society in Bandra West.",
        "property_type": PropertyType.residential,
        "property_subtype": PropertySubtype.flat,
        "address": "Flat 1201, Sea Breeze Heights, Carter Road, Bandra West",
        "locality": "Bandra West",
        "city": "Mumbai",
        "state": "Maharashtra",
        "pin_code": "400050",
        "reserve_price": 45000000,
        "emd_amount": 4500000,
        "bid_increment": 500000,
        "auction_date": date(2026, 5, 10),
        "auction_time": "11:00 AM",
        "possession_status": PossessionStatus.symbolic,
        "area_sqft": 1100,
        "contact_person": "Mr. K. Desai",
        "contact_phone": "022-26543210",
    },
    {
        "bank_name": "Indian Overseas Bank",
        "bank_branch": "Anna Nagar Branch",
        "title": "Commercial Building in Anna Nagar, Chennai",
        "description": "4-storey commercial building suitable for offices or retail.",
        "property_type": PropertyType.commercial,
        "property_subtype": PropertySubtype.building,
        "address": "No 45, 2nd Avenue, Anna Nagar",
        "locality": "Anna Nagar",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "pin_code": "600040",
        "reserve_price": 28000000,
        "emd_amount": 2800000,
        "bid_increment": 200000,
        "auction_date": date(2026, 5, 8),
        "auction_time": "2:00 PM",
        "possession_status": PossessionStatus.physical,
        "area_sqft": 5000,
        "contact_person": "Mr. M. Subramaniam",
        "contact_phone": "044-26543210",
    },
    {
        "bank_name": "UCO Bank",
        "bank_branch": "Sector 17 Branch",
        "title": "Residential Plot in Sector 49, Chandigarh",
        "description": "Premium residential plot in a well-developed sector of Chandigarh.",
        "property_type": PropertyType.land,
        "property_subtype": PropertySubtype.plot,
        "address": "Plot No 234, Sector 49-C",
        "locality": "Sector 49",
        "city": "Chandigarh",
        "state": "Chandigarh",
        "pin_code": "160047",
        "reserve_price": 12000000,
        "emd_amount": 1200000,
        "bid_increment": 100000,
        "auction_date": date(2026, 5, 12),
        "auction_time": "10:00 AM",
        "possession_status": PossessionStatus.physical,
        "area_sqft": 3000,
        "contact_person": "Mr. G. Singh",
        "contact_phone": "0172-2654321",
    },
    {
        "bank_name": "State Bank of India",
        "bank_branch": "Bhubaneswar Branch",
        "title": "2BHK Flat in Patia, Bhubaneswar",
        "description": "Modern 2BHK in a gated complex near Infocity.",
        "property_type": PropertyType.residential,
        "property_subtype": PropertySubtype.flat,
        "address": "Flat C-304, Utkal Heights, Patia",
        "locality": "Patia",
        "city": "Bhubaneswar",
        "state": "Odisha",
        "pin_code": "751024",
        "reserve_price": 3200000,
        "emd_amount": 320000,
        "bid_increment": 25000,
        "auction_date": date(2026, 4, 30),
        "auction_time": "11:00 AM",
        "possession_status": PossessionStatus.symbolic,
        "area_sqft": 850,
        "contact_person": "Mr. P. Mohanty",
        "contact_phone": "0674-2543210",
    },
    {
        "bank_name": "Axis Bank",
        "bank_branch": "MG Road Branch",
        "title": "Factory Unit in Peenya, Bangalore",
        "description": "Industrial factory unit in Peenya Industrial Area with power and water supply.",
        "property_type": PropertyType.industrial,
        "property_subtype": PropertySubtype.factory,
        "address": "Unit 12, Peenya Industrial Area, 2nd Stage",
        "locality": "Peenya",
        "city": "Bangalore",
        "state": "Karnataka",
        "pin_code": "560058",
        "reserve_price": 18000000,
        "emd_amount": 1800000,
        "bid_increment": 100000,
        "auction_date": date(2026, 5, 15),
        "auction_time": "3:00 PM",
        "possession_status": PossessionStatus.physical,
        "area_sqft": 8000,
        "contact_person": "Mr. N. Gowda",
        "contact_phone": "080-28765432",
    },
    {
        "bank_name": "Punjab National Bank",
        "bank_branch": "Vaishali Branch",
        "title": "Agricultural Land in Noida Extension",
        "description": "Agricultural land with road access. Potential for development subject to conversion.",
        "property_type": PropertyType.agricultural,
        "property_subtype": PropertySubtype.plot,
        "address": "Khasra No 45, Village Bisrakh, Greater Noida",
        "locality": "Greater Noida",
        "city": "Noida",
        "state": "Uttar Pradesh",
        "pin_code": "201306",
        "reserve_price": 7500000,
        "emd_amount": 750000,
        "bid_increment": 50000,
        "auction_date": date(2026, 5, 3),
        "auction_time": "12:00 PM",
        "possession_status": PossessionStatus.physical,
        "area_sqft": 43560,
        "contact_person": "Mr. H. Verma",
        "contact_phone": "0120-4567890",
    },
    {
        "bank_name": "HDFC Bank",
        "bank_branch": "Viman Nagar Branch",
        "title": "2BHK Flat in Kharadi, Pune",
        "description": "Modern 2BHK apartment in an IT corridor. Close to EON IT Park.",
        "property_type": PropertyType.residential,
        "property_subtype": PropertySubtype.flat,
        "address": "Flat 501, Blue Ridge Township, Kharadi",
        "locality": "Kharadi",
        "city": "Pune",
        "state": "Maharashtra",
        "pin_code": "411014",
        "reserve_price": 6800000,
        "emd_amount": 680000,
        "bid_increment": 50000,
        "auction_date": date(2026, 5, 6),
        "auction_time": "11:00 AM",
        "possession_status": PossessionStatus.symbolic,
        "area_sqft": 1050,
        "contact_person": "Ms. S. Joshi",
        "contact_phone": "020-67654321",
    },
    {
        "bank_name": "Bank of Baroda",
        "bank_branch": "Vastrapur Branch",
        "title": "Office Space in Prahlad Nagar, Ahmedabad",
        "description": "Ready-to-use office space with furnishing. Corporate Park location.",
        "property_type": PropertyType.commercial,
        "property_subtype": PropertySubtype.office,
        "address": "Office 301, Corporate House, Prahlad Nagar",
        "locality": "Prahlad Nagar",
        "city": "Ahmedabad",
        "state": "Gujarat",
        "pin_code": "380015",
        "reserve_price": 8000000,
        "emd_amount": 800000,
        "bid_increment": 50000,
        "auction_date": date(2026, 5, 2),
        "auction_time": "2:00 PM",
        "possession_status": PossessionStatus.physical,
        "area_sqft": 1500,
        "contact_person": "Mr. B. Shah",
        "contact_phone": "079-27654321",
    },
    {
        "bank_name": "ICICI Bank",
        "bank_branch": "Electronic City Branch",
        "title": "1BHK Flat in Electronic City, Bangalore",
        "description": "Affordable 1BHK apartment near Infosys campus, Electronic City Phase 1.",
        "property_type": PropertyType.residential,
        "property_subtype": PropertySubtype.flat,
        "address": "Flat 102, Prestige Lakeside, Electronic City Phase 1",
        "locality": "Electronic City",
        "city": "Bangalore",
        "state": "Karnataka",
        "pin_code": "560100",
        "reserve_price": 3500000,
        "emd_amount": 350000,
        "bid_increment": 25000,
        "auction_date": date(2026, 4, 29),
        "auction_time": "10:30 AM",
        "possession_status": PossessionStatus.symbolic,
        "area_sqft": 650,
        "contact_person": "Ms. R. Hegde",
        "contact_phone": "080-41654321",
    },
    {
        "bank_name": "State Bank of India",
        "bank_branch": "C-Scheme Branch",
        "title": "Showroom on MI Road, Jaipur",
        "description": "Prime showroom space on MI Road. High footfall commercial area.",
        "property_type": PropertyType.commercial,
        "property_subtype": PropertySubtype.shop,
        "address": "Ground Floor, Rajmahal Plaza, MI Road",
        "locality": "MI Road",
        "city": "Jaipur",
        "state": "Rajasthan",
        "pin_code": "302001",
        "reserve_price": 16000000,
        "emd_amount": 1600000,
        "bid_increment": 100000,
        "auction_date": date(2026, 5, 7),
        "auction_time": "11:00 AM",
        "possession_status": PossessionStatus.physical,
        "area_sqft": 1800,
        "contact_person": "Mr. L. Meena",
        "contact_phone": "0141-2654321",
    },
    {
        "bank_name": "Canara Bank",
        "bank_branch": "Indira Nagar Branch",
        "title": "3BHK Flat in Indira Nagar, Bangalore",
        "description": "Premium 3BHK in Indira Nagar with modern amenities and club house.",
        "property_type": PropertyType.residential,
        "property_subtype": PropertySubtype.flat,
        "address": "Flat 802, Sobha Indraprastha, 100 Feet Road, Indira Nagar",
        "locality": "Indira Nagar",
        "city": "Bangalore",
        "state": "Karnataka",
        "pin_code": "560038",
        "reserve_price": 19500000,
        "emd_amount": 1950000,
        "bid_increment": 100000,
        "auction_date": date(2026, 5, 14),
        "auction_time": "10:00 AM",
        "possession_status": PossessionStatus.symbolic,
        "area_sqft": 1850,
        "contact_person": "Mr. S. Rao",
        "contact_phone": "080-25654321",
    },
    {
        "bank_name": "Union Bank of India",
        "bank_branch": "Banjara Hills Branch",
        "title": "Commercial Building in Banjara Hills, Hyderabad",
        "description": "Multi-storey commercial building in Banjara Hills. High rental yield potential.",
        "property_type": PropertyType.commercial,
        "property_subtype": PropertySubtype.building,
        "address": "Road No 12, Banjara Hills",
        "locality": "Banjara Hills",
        "city": "Hyderabad",
        "state": "Telangana",
        "pin_code": "500034",
        "reserve_price": 52000000,
        "emd_amount": 5200000,
        "bid_increment": 500000,
        "auction_date": date(2026, 5, 20),
        "auction_time": "2:00 PM",
        "possession_status": PossessionStatus.physical,
        "area_sqft": 8500,
        "contact_person": "Mr. K. Reddy",
        "contact_phone": "040-23654321",
    },
    {
        "bank_name": "Indian Bank",
        "bank_branch": "Adyar Branch",
        "title": "2BHK Flat in Adyar, Chennai",
        "description": "Well-maintained 2BHK in Adyar near IIT Madras. Good rental demand.",
        "property_type": PropertyType.residential,
        "property_subtype": PropertySubtype.flat,
        "address": "Flat 3A, Lakshmi Apartments, 2nd Main Road, Adyar",
        "locality": "Adyar",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "pin_code": "600020",
        "reserve_price": 7200000,
        "emd_amount": 720000,
        "bid_increment": 50000,
        "auction_date": date(2026, 5, 11),
        "auction_time": "11:00 AM",
        "possession_status": PossessionStatus.symbolic,
        "area_sqft": 1100,
        "contact_person": "Mr. V. Krishnan",
        "contact_phone": "044-24543210",
    },
]


async def seed_database():
    """Create initial data in the database."""
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with async_session_factory() as db:
        # Seed subscription plans
        for plan_data in SUBSCRIPTION_PLANS:
            existing = await db.execute(
                select(SubscriptionPlan).where(SubscriptionPlan.name == plan_data["name"])
            )
            if not existing.scalar_one_or_none():
                plan = SubscriptionPlan(**plan_data)
                db.add(plan)
        await db.flush()

        # Get free plan for admin
        free_plan_result = await db.execute(
            select(SubscriptionPlan).where(SubscriptionPlan.name == "Free")
        )
        free_plan = free_plan_result.scalar_one_or_none()

        # Seed admin user
        existing_admin = await db.execute(
            select(User).where(User.email == settings.ADMIN_EMAIL)
        )
        if not existing_admin.scalar_one_or_none():
            admin = User(
                email=settings.ADMIN_EMAIL,
                password_hash=hash_password(settings.ADMIN_PASSWORD),
                full_name="Platform Admin",
                role=UserRole.superadmin,
                subscription_plan_id=free_plan.id if free_plan else None,
            )
            db.add(admin)

        # Seed sources
        for source_data in SOURCES:
            existing = await db.execute(
                select(Source).where(Source.name == source_data["name"])
            )
            if not existing.scalar_one_or_none():
                source = Source(**source_data)
                db.add(source)

        # Seed sample properties
        existing_count = await db.execute(select(AuctionProperty.id).limit(1))
        if not existing_count.scalar_one_or_none():
            for prop_data in SAMPLE_PROPERTIES:
                prop = AuctionProperty(status=AuctionStatus.active, **prop_data)
                db.add(prop)

        await db.commit()
        print(f"Seeded: {len(SUBSCRIPTION_PLANS)} plans, {len(SOURCES)} sources, "
              f"{len(SAMPLE_PROPERTIES)} properties, 1 admin user")


if __name__ == "__main__":
    asyncio.run(seed_database())
